/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;

import javax.swing.JOptionPane;
/**
 *
 * @author Acer
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PatientB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        StaffB = new javax.swing.JButton();
        PaymentB = new javax.swing.JButton();
        MedicineB = new javax.swing.JButton();
        DoctorB = new javax.swing.JButton();
        InformationB = new javax.swing.JButton();
        ChannelB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        logoutB = new javax.swing.JButton();
        SettingsButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("HOSPITAL MANAGEMENT SYSTEM");
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 610, 60));

        PatientB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/patient.jpg"))); // NOI18N
        PatientB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientBActionPerformed(evt);
            }
        });
        getContentPane().add(PatientB, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 167, 234, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Patient Details");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, 30));

        StaffB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/staff.jpg"))); // NOI18N
        StaffB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffBActionPerformed(evt);
            }
        });
        getContentPane().add(StaffB, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 167, 238, -1));

        PaymentB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/paydetails.jpg"))); // NOI18N
        PaymentB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentBActionPerformed(evt);
            }
        });
        getContentPane().add(PaymentB, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 495, 237, -1));

        MedicineB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/Medicine.jpg"))); // NOI18N
        MedicineB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicineBActionPerformed(evt);
            }
        });
        getContentPane().add(MedicineB, new org.netbeans.lib.awtextra.AbsoluteConstraints(995, 167, 265, 233));

        DoctorB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/doctor.jpg"))); // NOI18N
        DoctorB.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DoctorB.setMargin(new java.awt.Insets(4, 16, 4, 16));
        DoctorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorBActionPerformed(evt);
            }
        });
        getContentPane().add(DoctorB, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 167, 236, -1));

        InformationB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/hosInfo.png"))); // NOI18N
        InformationB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformationBActionPerformed(evt);
            }
        });
        getContentPane().add(InformationB, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 495, 230, -1));

        ChannelB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/channelpati.jpg"))); // NOI18N
        ChannelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChannelBActionPerformed(evt);
            }
        });
        getContentPane().add(ChannelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 495, 248, 233));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Staff Details");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Medicine Information");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Payment Information");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 740, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("Manage Channels");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 740, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Doctor Details");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("Hospital Information");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 730, -1, -1));

        logoutB.setBackground(new java.awt.Color(255, 255, 255));
        logoutB.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        logoutB.setForeground(new java.awt.Color(102, 0, 51));
        logoutB.setText("Logout");
        logoutB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBActionPerformed(evt);
            }
        });
        getContentPane().add(logoutB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 710, 180, 52));

        SettingsButton.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        SettingsButton.setForeground(new java.awt.Color(102, 0, 51));
        SettingsButton.setText("Settings");
        SettingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingsButtonMouseClicked(evt);
            }
        });
        getContentPane().add(SettingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 600, 180, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/mainbackground.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 790));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1AncestorAdded

    private void PatientBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientBActionPerformed
        // TODO add your handling code here:
        new Patient().setVisible(true);
        
    }//GEN-LAST:event_PatientBActionPerformed

    private void DoctorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorBActionPerformed
        // TODO add your handling code here:
        new Doctor().setVisible(true);
    }//GEN-LAST:event_DoctorBActionPerformed

    private void StaffBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffBActionPerformed
        // TODO add your handling code here:
        new Staff().setVisible(true);
    }//GEN-LAST:event_StaffBActionPerformed

    private void MedicineBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicineBActionPerformed
        // TODO add your handling code here:
        new Medicine().setVisible(true);
    }//GEN-LAST:event_MedicineBActionPerformed

    private void PaymentBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentBActionPerformed
        // TODO add your handling code here:
        new Payment().setVisible(true);
    }//GEN-LAST:event_PaymentBActionPerformed

    private void logoutBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to logout", "Select",JOptionPane.YES_NO_OPTION );
        if(a == 0)
            setVisible(false);
            new login().setVisible(true);
    }//GEN-LAST:event_logoutBActionPerformed

    private void ChannelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChannelBActionPerformed
        // TODO add your handling code here:
        new Channel().setVisible(true);
    }//GEN-LAST:event_ChannelBActionPerformed

    private void InformationBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformationBActionPerformed
        // TODO add your handling code here:
        new Information().setVisible(true);
    }//GEN-LAST:event_InformationBActionPerformed

    private void SettingsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsButtonMouseClicked
        // TODO add your handling code here:
        new Settings().setVisible(true);
    }//GEN-LAST:event_SettingsButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChannelB;
    private javax.swing.JButton DoctorB;
    private javax.swing.JButton InformationB;
    private javax.swing.JButton MedicineB;
    private javax.swing.JButton PatientB;
    private javax.swing.JButton PaymentB;
    private javax.swing.JButton SettingsButton;
    private javax.swing.JButton StaffB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton logoutB;
    // End of variables declaration//GEN-END:variables
}
